/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class DistinctTypesResponse implements Serializable {


    @ColumnAlias("ORG_TYPE")
    private String orgType;

    public String getOrgType() {
        return this.orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DistinctTypesResponse)) return false;
        final DistinctTypesResponse distinctTypesResponse = (DistinctTypesResponse) o;
        return Objects.equals(getOrgType(), distinctTypesResponse.getOrgType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrgType());
    }
}