/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.meforwe.meforwe.Campaigns;


/**
 * ServiceImpl object for domain model class Campaigns.
 *
 * @see Campaigns
 */
@Service("meforwe.CampaignsService")
@Validated
public class CampaignsServiceImpl implements CampaignsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CampaignsServiceImpl.class);


    @Autowired
    @Qualifier("meforwe.CampaignsDao")
    private WMGenericDao<Campaigns, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Campaigns, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "meforweTransactionManager")
    @Override
    public Campaigns create(Campaigns campaigns) {
        LOGGER.debug("Creating a new Campaigns with information: {}", campaigns);

        Campaigns campaignsCreated = this.wmGenericDao.create(campaigns);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(campaignsCreated);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Campaigns getById(Integer campaignsId) {
        LOGGER.debug("Finding Campaigns by id: {}", campaignsId);
        return this.wmGenericDao.findById(campaignsId);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Campaigns findById(Integer campaignsId) {
        LOGGER.debug("Finding Campaigns by id: {}", campaignsId);
        try {
            return this.wmGenericDao.findById(campaignsId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Campaigns found with id: {}", campaignsId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public List<Campaigns> findByMultipleIds(List<Integer> campaignsIds, boolean orderedReturn) {
        LOGGER.debug("Finding Campaigns by ids: {}", campaignsIds);

        return this.wmGenericDao.findByMultipleIds(campaignsIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "meforweTransactionManager")
    @Override
    public Campaigns update(Campaigns campaigns) {
        LOGGER.debug("Updating Campaigns with information: {}", campaigns);

        this.wmGenericDao.update(campaigns);
        this.wmGenericDao.refresh(campaigns);

        return campaigns;
    }

    @Transactional(value = "meforweTransactionManager")
    @Override
    public Campaigns delete(Integer campaignsId) {
        LOGGER.debug("Deleting Campaigns with id: {}", campaignsId);
        Campaigns deleted = this.wmGenericDao.findById(campaignsId);
        if (deleted == null) {
            LOGGER.debug("No Campaigns found with id: {}", campaignsId);
            throw new EntityNotFoundException(String.valueOf(campaignsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "meforweTransactionManager")
    @Override
    public void delete(Campaigns campaigns) {
        LOGGER.debug("Deleting Campaigns with {}", campaigns);
        this.wmGenericDao.delete(campaigns);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Page<Campaigns> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Campaigns");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Page<Campaigns> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Campaigns");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service meforwe for table Campaigns to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service meforwe for table Campaigns to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}