/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.time.LocalDateTime;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.meforwe.meforwe.models.query.*;

public interface MeforweQueryExecutorService {

    Page<MapFilterResponse> executeMapFilter(LocalDateTime dt, Integer zc, Pageable pageable);

    void exportMapFilter(LocalDateTime dt, Integer zc, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<DistinctTypesResponse> executeDistinct_types(Pageable pageable);

    void exportDistinct_types(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<TodayEventsResponse> executeTodayEvents(Pageable pageable);

    void exportTodayEvents(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}