/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.meforwe.meforwe.OrgLocations;

/**
 * Service object for domain model class {@link OrgLocations}.
 */
public interface OrgLocationsService {

    /**
     * Creates a new OrgLocations. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on OrgLocations if any.
     *
     * @param orgLocations Details of the OrgLocations to be created; value cannot be null.
     * @return The newly created OrgLocations.
     */
    OrgLocations create(@Valid OrgLocations orgLocations);


	/**
     * Returns OrgLocations by given id if exists.
     *
     * @param orglocationsId The id of the OrgLocations to get; value cannot be null.
     * @return OrgLocations associated with the given orglocationsId.
	 * @throws EntityNotFoundException If no OrgLocations is found.
     */
    OrgLocations getById(Integer orglocationsId);

    /**
     * Find and return the OrgLocations by given id if exists, returns null otherwise.
     *
     * @param orglocationsId The id of the OrgLocations to get; value cannot be null.
     * @return OrgLocations associated with the given orglocationsId.
     */
    OrgLocations findById(Integer orglocationsId);

	/**
     * Find and return the list of OrgLocations by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param orglocationsIds The id's of the OrgLocations to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return OrgLocations associated with the given orglocationsIds.
     */
    List<OrgLocations> findByMultipleIds(List<Integer> orglocationsIds, boolean orderedReturn);


    /**
     * Updates the details of an existing OrgLocations. It replaces all fields of the existing OrgLocations with the given orgLocations.
     *
     * This method overrides the input field values using Server side or database managed properties defined on OrgLocations if any.
     *
     * @param orgLocations The details of the OrgLocations to be updated; value cannot be null.
     * @return The updated OrgLocations.
     * @throws EntityNotFoundException if no OrgLocations is found with given input.
     */
    OrgLocations update(@Valid OrgLocations orgLocations);

    /**
     * Deletes an existing OrgLocations with the given id.
     *
     * @param orglocationsId The id of the OrgLocations to be deleted; value cannot be null.
     * @return The deleted OrgLocations.
     * @throws EntityNotFoundException if no OrgLocations found with the given id.
     */
    OrgLocations delete(Integer orglocationsId);

    /**
     * Deletes an existing OrgLocations with the given object.
     *
     * @param orgLocations The instance of the OrgLocations to be deleted; value cannot be null.
     */
    void delete(OrgLocations orgLocations);

    /**
     * Find all OrgLocations matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OrgLocations.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<OrgLocations> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all OrgLocations matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OrgLocations.
     *
     * @see Pageable
     * @see Page
     */
    Page<OrgLocations> findAll(String query, Pageable pageable);

    /**
     * Exports all OrgLocations matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all OrgLocations matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the OrgLocations in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the OrgLocations.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}