/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.meforwe.meforwe.Orgs;


/**
 * ServiceImpl object for domain model class Orgs.
 *
 * @see Orgs
 */
@Service("meforwe.OrgsService")
@Validated
public class OrgsServiceImpl implements OrgsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(OrgsServiceImpl.class);


    @Autowired
    @Qualifier("meforwe.OrgsDao")
    private WMGenericDao<Orgs, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Orgs, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "meforweTransactionManager")
    @Override
    public Orgs create(Orgs orgs) {
        LOGGER.debug("Creating a new Orgs with information: {}", orgs);

        Orgs orgsCreated = this.wmGenericDao.create(orgs);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(orgsCreated);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Orgs getById(Integer orgsId) {
        LOGGER.debug("Finding Orgs by id: {}", orgsId);
        return this.wmGenericDao.findById(orgsId);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Orgs findById(Integer orgsId) {
        LOGGER.debug("Finding Orgs by id: {}", orgsId);
        try {
            return this.wmGenericDao.findById(orgsId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Orgs found with id: {}", orgsId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public List<Orgs> findByMultipleIds(List<Integer> orgsIds, boolean orderedReturn) {
        LOGGER.debug("Finding Orgs by ids: {}", orgsIds);

        return this.wmGenericDao.findByMultipleIds(orgsIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "meforweTransactionManager")
    @Override
    public Orgs update(Orgs orgs) {
        LOGGER.debug("Updating Orgs with information: {}", orgs);

        this.wmGenericDao.update(orgs);
        this.wmGenericDao.refresh(orgs);

        return orgs;
    }

    @Transactional(value = "meforweTransactionManager")
    @Override
    public Orgs delete(Integer orgsId) {
        LOGGER.debug("Deleting Orgs with id: {}", orgsId);
        Orgs deleted = this.wmGenericDao.findById(orgsId);
        if (deleted == null) {
            LOGGER.debug("No Orgs found with id: {}", orgsId);
            throw new EntityNotFoundException(String.valueOf(orgsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "meforweTransactionManager")
    @Override
    public void delete(Orgs orgs) {
        LOGGER.debug("Deleting Orgs with {}", orgs);
        this.wmGenericDao.delete(orgs);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Page<Orgs> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Orgs");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Page<Orgs> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Orgs");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service meforwe for table Orgs to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service meforwe for table Orgs to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "meforweTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}