/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Campaigns generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`CAMPAIGNS`")
public class Campaigns implements Serializable {

    private Integer id;
    private String campaignName;
    private String campaignDesc;
    private String createdBy;
    private LocalDateTime date;
    private Integer createdById;
    private String address;
    private Integer zip;
    private Integer likes;
    private Integer disLikes;
    private BigInteger amountReceived;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`CAMPAIGN_NAME`", nullable = true, length = 255)
    public String getCampaignName() {
        return this.campaignName;
    }

    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    @Column(name = "`CAMPAIGN_DESC`", nullable = true, length = 255)
    public String getCampaignDesc() {
        return this.campaignDesc;
    }

    public void setCampaignDesc(String campaignDesc) {
        this.campaignDesc = campaignDesc;
    }

    @Column(name = "`CREATED_BY`", nullable = true, length = 255)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "`DATE`", nullable = true)
    public LocalDateTime getDate() {
        return this.date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    @Column(name = "`CREATED_BY_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getCreatedById() {
        return this.createdById;
    }

    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    @Column(name = "`ADDRESS`", nullable = true, length = 1000)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "`ZIP`", nullable = true, scale = 0, precision = 10)
    public Integer getZip() {
        return this.zip;
    }

    public void setZip(Integer zip) {
        this.zip = zip;
    }

    @Column(name = "`LIKES`", nullable = true, scale = 0, precision = 10)
    public Integer getLikes() {
        return this.likes;
    }

    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    @Column(name = "`DIS_LIKES`", nullable = true, scale = 0, precision = 10)
    public Integer getDisLikes() {
        return this.disLikes;
    }

    public void setDisLikes(Integer disLikes) {
        this.disLikes = disLikes;
    }

    @Column(name = "`AMOUNT_RECEIVED`", nullable = true, scale = 0, precision = 10)
    public BigInteger getAmountReceived() {
        return this.amountReceived;
    }

    public void setAmountReceived(BigInteger amountReceived) {
        this.amountReceived = amountReceived;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Campaigns)) return false;
        final Campaigns campaigns = (Campaigns) o;
        return Objects.equals(getId(), campaigns.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}