/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.meforwe.meforwe;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orgs generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ORGS`")
public class Orgs implements Serializable {

    private Integer orgId;
    private String orgName;
    private String orgAddress;
    private String orgLink;
    private String orgType;
    private Integer zipCode;
    private String imageLink;
    private BigInteger orgPhone;
    private String orgDesc;
    private Float rating;
    private BigInteger amountReceived;
    private String smallIcon;
    private String utube;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ORG_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getOrgId() {
        return this.orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    @Column(name = "`ORG_NAME`", nullable = true, length = 255)
    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @Column(name = "`ORG_ADDRESS`", nullable = true, length = 255)
    public String getOrgAddress() {
        return this.orgAddress;
    }

    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress;
    }

    @Column(name = "`ORG_LINK`", nullable = true, length = 255)
    public String getOrgLink() {
        return this.orgLink;
    }

    public void setOrgLink(String orgLink) {
        this.orgLink = orgLink;
    }

    @Column(name = "`ORG_TYPE`", nullable = true, length = 255)
    public String getOrgType() {
        return this.orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    @Column(name = "`ZIP_CODE`", nullable = true, scale = 0, precision = 10)
    public Integer getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    @Column(name = "`IMAGE_LINK`", nullable = true, length = 255)
    public String getImageLink() {
        return this.imageLink;
    }

    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }

    @Column(name = "`ORG_PHONE`", nullable = true, scale = 0, precision = 10)
    public BigInteger getOrgPhone() {
        return this.orgPhone;
    }

    public void setOrgPhone(BigInteger orgPhone) {
        this.orgPhone = orgPhone;
    }

    @Column(name = "`ORG_DESC`", nullable = true, length = 1000)
    public String getOrgDesc() {
        return this.orgDesc;
    }

    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc;
    }

    @Column(name = "`RATING`", nullable = true, scale = 0, precision = 10)
    public Float getRating() {
        return this.rating;
    }

    public void setRating(Float rating) {
        this.rating = rating;
    }

    @Column(name = "`AMOUNT_RECEIVED`", nullable = true, scale = 0, precision = 10)
    public BigInteger getAmountReceived() {
        return this.amountReceived;
    }

    public void setAmountReceived(BigInteger amountReceived) {
        this.amountReceived = amountReceived;
    }

    @Column(name = "`SMALL_ICON`", nullable = true, length = 1000)
    public String getSmallIcon() {
        return this.smallIcon;
    }

    public void setSmallIcon(String smallIcon) {
        this.smallIcon = smallIcon;
    }

    @Column(name = "`UTUBE`", nullable = true, length = 2147483647)
    public String getUtube() {
        return this.utube;
    }

    public void setUtube(String utube) {
        this.utube = utube;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Orgs)) return false;
        final Orgs orgs = (Orgs) o;
        return Objects.equals(getOrgId(), orgs.getOrgId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrgId());
    }
}